# todolist micro-service on mongo
bookstore-mongo:
  container_name: todolist-mongo
  image: xavmarc/todolist:latest
  restart: always
  environment:
    - URL_DB=${URL_DB}
  links:
    - mongo
  ports:
    - "8020:8020"
  command: -port 8020 -db 1 -statd 5m

# bdd mongo
mongo:
  container_name: todolist-mongo-db
  image: mongo:latest
  restart: always
  ports:
    - "27017:27017"