# Gopkg.toml example
# version = "2.4.0"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "gopkg.in/redis.v5"
  version = "5.2.9"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"
