[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.3.0"
  
[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "gopkg.in/redis.v5"
  version = "5.2.9"